### ISSUE TITLE
Synchronize treks with filter 

### ISSUE THREAD

**Issue by leplatrem** [GeotrekCE/Geotrek-rando#127]
For example, synchronize by structure, so that each structure can have its own public website

Related : 
https://github.com/makinacorpus/Geotrek/issues/1011
https://github.com/makinacorpus/Geotrek/issues/1013

**Comment by camillemonchicourt** [comment]
Geotrek-admin synchronization now allows to filter by source or portal since a few versions. 
Documentation at https://geotrek.readthedocs.io/en/master/synchronization.html#synchronization-filtered-by-source-and-portal
