### ISSUE TITLE
BUILD MOBILE DATA generate trek tiles each time even if treks didnt changed

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-rando#322]
When we launch `bin/python ./manage.py build_mobile_data http://rando.ecrins-parcnational.fr` it looks like every trek tiles are generated each times. Even if they didnt changed.
Is it normal and necessary ?

Same for `/var/input/tiles/global.zip` ?

**Comment by camillemonchicourt** [comment]
Après un nouveau test, il semblerait qu'il fasse cela uniquement quand UNE rando change. Mais il régénère les tuiles pour toutes les randos dans ``var/input/tiles``

Par contre le ``global.zip`` est bien régénéré à chaque fois même si aucune rando n'a changé.

**Comment by gutard** [comment]
We don't know when tiles change or not. So build_mobile_data always build tiles. But you can add --no-tiles option to skip this step in your daily cron and build tiles manually from time to time.

**Comment by camillemonchicourt** [comment]
OK thanks a lot for this info. Perfect !

**Comment by leplatrem** [comment]
I guess that tile servers return 304 when If-Modified-Since is passed, no?

Also maybe, a checksum comparison between old and new global.zip could help preventing to refresh data on user devices when nothing changed, no?

**Comment by gutard** [comment]
IIRC, tile are regenerated frequently so 304 is returned only during a too short period (maybe 24h).
The checksum method is already used for trek data and could be used for tiles.

**Comment by camillemonchicourt** [comment]
OK as actually I launch ``bin/python ./manage.py build_mobile_data http://rando.ecrins-parcnational.fr`` automatically with a CRON each night. As mentionned in the documentation of Geotrek-rando (V1).
So each day when we launch RANDO ECRISN MOBILE, we get the message "Données mises à jour. Les données concernant les randonnées ont été mises à jour..." while datas didn't changed.
Just because he rebuilt the tiles so the APP interprets it as a data change.

So actually I will update my CRON, adding option ``--no-tiles`` but it can be a problem if someone change the geometry of a trek.

**Comment by gutard** [comment]
With v2, tiles zip files are build on Geotrek-Admin site and not modified if the trek did not changed.

**Comment by camillemonchicourt** [comment]
Related to V1, can be closed now. 
Mobile datas are now generated on Geotrek-admin.
