### ISSUE TITLE
V1 - Weblinks order group

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-rando#326]
It looks like there is a small problem in the ORDER of weblinks in treks detail pages on Geotrek-rando V1. 

Weblinks are grouped by category but not totally as it looks that orders depends on order of creation of links. 

Here is a preview of the problem where there is 2 groups LOCATION DE VELOS : 

![weblinks](https://cloud.githubusercontent.com/assets/4418840/8826897/d6bfbd9c-3089-11e5-8a47-e95e4089470d.jpg)

As Geotrek-rando V1 is not supposed to get new releases, but maybe someone have just the small HACK to fix it manually ?

Thanks.

**Comment by leplatrem** [comment]
I think you need to sort them first.
It's not a one-line fix. And V1.X would at least deserve bug fix releases...  

Try this (untested) :

1) Add ``context['sorted_weblinks'] = sorted(obj.properties.web_links, key=lambda x: x['category'])``
https://github.com/makinacorpus/Geotrek-rando/blob/v1.X/rando/trekking/views.py#L121

2) Replace ``object.properties.web_links`` by ``sorted_weblinks``
https://github.com/makinacorpus/Geotrek-rando/blob/v1.X/rando/trekking/templates/trekking/_detail_panel.html#L225
