### ISSUE TITLE
Translate Geotrek-rando in Italian

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-rando#354]
As discussed in Geotrek-mobile - https://github.com/makinacorpus/Geotrek-mobile/pull/134

@samuelpriou

**Comment by camillemonchicourt** [comment]
Geotrek-mobile is already translated in IT.

About Geotrek-rando, you can do it anytime with creating the IT version of this file : https://github.com/makinacorpus/Geotrek-rando/tree/master/src/app/translation/po/fr

Geotrek-rando V1 IT translation are in a few files in each module :

* https://github.com/makinacorpus/Geotrek-rando/blob/v1.X/rando/trekking/locale/it/LC_MESSAGES/django.po
* https://github.com/makinacorpus/Geotrek-rando/blob/v1.X/rando/core/locale/it/LC_MESSAGES/django.po
* https://github.com/makinacorpus/Geotrek-rando/blob/v1.X/rando/feedback/locale/it/LC_MESSAGES/django.po
* https://github.com/makinacorpus/Geotrek-rando/blob/v1.X/rando/flatpages/locale/it/LC_MESSAGES/django.po
* https://github.com/makinacorpus/Geotrek-rando/blob/v1.X/rando/view3d/locale/it/LC_MESSAGES/django.po

**Comment by lellex** [comment]
Done, but it's missing some translations

https://github.com/makinacorpus/Geotrek-rando/pull/378

**Comment by camillemonchicourt** [comment]
Any news about this point @samuelpriou ?

**Comment by camillemonchicourt** [comment]
Done in 2.16.1, @samuelpriou, be careful to keep it updated when new releases are published as they can include new terms.
