### ISSUE TITLE
Extend accessSpecificCategory function to the whole site

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-rando#575]
Actually we can only use it from HOMEPAGE. 
We included some link to SPECIFIC CATEGORIES in our global menu but then it only works when displayed on homepage - http://www.grand-tour-ecrins.fr/

**Comment by camillemonchicourt** [comment]
Fixed too in 2.14.3 ?

**Comment by SBats** [comment]
No

**Comment by camillemonchicourt** [comment]
OK so can be closed I guess.
