### ISSUE TITLE
Trek detail page - Switch language close POI panel

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-rando#584]
Example here - http://mtcv.ecrins-parcnational.com/a-pied/le-refuge-du-tourond/

**Comment by pacproduct** [comment]
The new behavior is as follows:
Whenever the list of results on the right sidebar gest reloaded (which happens when switching language), the default category accordion gets toggled *only if* none of them is open. That is: if one's already open, we leave it as it is.

**Comment by camillemonchicourt** [comment]
Thanks
