### ISSUE TITLE
Partage Facebook

### ISSUE THREAD

**Issue by thomaspnrhj** [GeotrekCE/Geotrek-rando#610]
Impossible de partager le G.Rando ou l'itinéraire sur Facebook via l’icône (problème à priori sur les autres G.Rando) malgré la conf de "FACEBOOK_APP_ID" dans settings.custom.json

**Comment by camillemonchicourt** [comment]
Tu as bien créé une application Facebook comme indiqué ici : https://github.com/GeotrekCE/Geotrek-rando/issues/330#issuecomment-175538312 ?

Ça fonctionne bien dans notre Geotrek-rando : http://www.grand-tour-ecrins.fr/a-pied/gr-54-au-depart-de-largentiere-la-bessee/

**Comment by thomaspnrhj** [comment]
Je n'avais pas activé l'appli (dernier point)...
