### ISSUE TITLE
Bug clavier après l'affichage 3D

### ISSUE THREAD

**Issue by GuillaumedeSury** [GeotrekCE/Geotrek-rando#613]
Ce bug apparaît après avoir fermé la fenêtre 3D, les touches "z,q,s,d" et les flèches de direction (utilisées pour la navigation en 3D) ne fonctionne plus. Le problème se pose si par exemple l'on souhaite faire un signalement ou une recherche. Le problème disparaît après avoir rechargé la page.

Testé sur la 2.16.2 sous Firefox et Chrome.

**Comment by pacproduct** [comment]
Proposition d'une correction dans la PR #634. Elle règle également le problème de performance rencontré une fois la modale 3D fermée : les ressources prises par le rendu de la scène sont maintenant libérée.

**Comment by camillemonchicourt** [comment]
Super
