### ISSUE TITLE
All CI builds are failing since a few weeks

### ISSUE THREAD

**Issue by mabhub** [GeotrekCE/Geotrek-rando#619]
From the end of August, TravisCI has [change the default linux distribution they're using](https://blog.travis-ci.com/2017-08-31-trusty-as-default-status), from _Precise_ to _Trusty_. Since then, all builds of Geotrek-rando are failling.

We need to update travis.yml to force using _Precise_.

**Comment by camillemonchicourt** [comment]
Thanks.
