### ISSUE TITLE
Routing par nom non unique

### ISSUE THREAD

**Issue by submarcos** [GeotrekCE/Geotrek-rando#658]
Pour le contenu touristique, les liens générés sont du type : 

/contenu-touristique/\<nom-du-contenu\>/

Le problème, c'est que rien n'interdit à l'admin de spécifier deux contenus avec le meme nom.

Il faudrait soit y ajouter l'id de l'élément, soit à minima prendre en compte la catégorie de contenu touristique dans l'url

Conséquences : si deux contenus de différentes catégories ont le même nom, ils seront bien listés, mais seul le premier sera accessible

**Comment by camillemonchicourt** [comment]
Exact et ça a été revu recemment : https://github.com/GeotrekCE/Geotrek-rando/issues/614

**Comment by submarcos** [comment]
çà a été annulé par gael. du coup toujours d'actualité

**Comment by camillemonchicourt** [comment]
Ah OK !
