### ISSUE TITLE
Retour à la carte et filtres

### ISSUE THREAD

**Issue by submarcos** [GeotrekCE/Geotrek-rando#659]
Depuis la version 2.19.0, le bouton "retour à la carte" ne fonctionne pas comme il faut si des filtres sont actifs.
Le retour à la carte se fait, mais le spinner de chargement ne s'efface jamais et impossible de reprendre la main sur l'outil sans recharger manuellement

**Comment by camillemonchicourt** [comment]
Corrigé.
