### ISSUE TITLE
Problème à l’exécution du script Gulp dans la commande npm run dist

### ISSUE THREAD

**Issue by DELOUSTAL** [GeotrekCE/Geotrek-rando#661]
J'ai installé Geotrek-admin 2.20.1 sur Ubuntu 18.04. L’application fonctionne.
Je commence l'installation de Geotrek-rando 2.19.1
Après avoir installé NodeJS v8.10.0 et Npm dans le dossier Geotrek -rando v3.5.2, ,
Au lancement de la commande npm run dist
l'installation s’arrête parce qu'il y a un problème dans le script Gulp.
En pièce jointe les fichiers command npm run dist.txt  (terminal) et le log npm-debug.log

[commande npm run dist.txt](https://github.com/GeotrekCE/Geotrek-rando/files/2284316/commande.npm.run.dist.txt)
[npm-debug.log](https://github.com/GeotrekCE/Geotrek-rando/files/2284317/npm-debug.log)

Remarque : dans la doc d'installation de Geotrek-rando , j'ai rencontré plusieurs erreurs
De plus la commande 
curl -sL https://deb.nodesource.com/setup_6.14.1 | sudo -E bash -
ne semble pas fonctionner. Le fichier .nvrmc indiquait la version 6.14.1 de NodeJS
J'ai opté pour un sudo apt install nodejs

Bien cordialement,

**Comment by camillemonchicourt** [comment]
C'est peut-être du au fait qu'il faut utiliser Node JS version 6 actuellement. 

Voir https://github.com/GeotrekCE/Geotrek-rando/blob/master/docs/install-node.md et le fichier https://github.com/GeotrekCE/Geotrek-rando/blob/master/.nvmrc comme indiqué dans cette partie de la documentation : https://github.com/GeotrekCE/Geotrek-rando/blob/master/docs/README.md#prerequisites

**Comment by gutard** [comment]
> Remarque : dans la doc d'installation de Geotrek-rando , j'ai rencontré plusieurs erreurs

Quelle doc et quelles erreurs ? Comme l'a dit Camille, concernant l'installation de nodejs, la doc de référence est https://github.com/GeotrekCE/Geotrek-rando/blob/master/docs/install-node.md et indique donc de télécharger https://deb.nodesource.com/setup_6.x (**6.x**) et non https://deb.nodesource.com/setup_6.14.1 (**6.14.1**).

Le fichier .nvmrc indique effectivement 6.14.1 mais, en principe, c'est le numéro majeur (le plus à gauche) qui compte pour la compatibilité. Aucune chance que Geotrek-rando fonctionne avec node 8.x. Par contre, il n'y a pas de raison que ça ne fonctionne pas avec la dernière version 6.x, à savoir la 6.14.3.

**Comment by DELOUSTAL** [comment]
Bonjour Gael,

 

Merci pour cette réponse. En effet, j’avais mal interprété le sens de la commande :

https://deb.nodesource.com/setup_6.x

Pour moi, il fallait substituer à la lettre x la partie mineure de la version de nodeJS.

Comme cela ne marchait pas, j’ai fait une installation standard qui m’a amené une version 8.
Je suis en train d’essayer de me défaire de nodeJS en version 8 pour reprendre l’installation en version 6.

 

Quand je parle d’erreur dans la doc, je parle de « Geotrek-rando documentation » du 15 juin 2017, § Install build dependencies :

 

cd Geotrek-rando-*

npm install

 

le -* est probablement un coquille.

npm install ne semble pas fonctionner.

 

Peut-être faudrait-il ajouter l’explication que vous m’avez donnée sur la commande curl https://deb.nodesource.com/setup_6.x

 

Étant nouveau dans Ubuntu et Geotrek, mais avec une expérience de nombreux autres OS, j’ai noté tous les points où 

J’ai eu de la peine à comprendre la documentation d’installation. Cela peut peut-être vous intéresser pour améliore la doc.

Il ne s’agit pas d’une critique, mais d’une contribution positive.

 

Comme Camille (en copie de ce message) vous le confirmera, membre de la FFRP, je suis chargé d’une mission pour faire dialoguer notre SIG BDRAndo avec l’application Geotrek-admin qu’utilise notre comité

départemental des Hautes-Alpes pour la collecte numérique. J’essaye en faisant une installation complète de Geotrek d’intéresser la FFRP à sa possible utilisation, pas pour notre collecte numérique,

mais pour la création de site web et sur d’app Rando mobile pour nos comités départementaux.

 

Je sais qu’il y a eu une rencontre entre Séverine Ikkawi et Makina-Korpus.

Peu de choses ont filtré de cette rencontre, mais des échos partiels que j’ai eus, il me semble que le message Geotrek est passé moyennement.

Si cela vous intéresse, on pourrait en parler téléphoniquement.

 

Encore merci pour votre aide.

 

Bien cordialement,

 

 

 

Pierre DELOUSTAL

Formateur Programme Numérique

 

15, rue du Pelvoux

05000 - GAP

Mail : pdeloustal@ffrandonnee.fr

Mobile : +33 (0) 607 11 96 04

Fixe  :    +33 (0) 492 23 61 29

 

 

 

 

 

 

 

De : Gaël UTARD <notifications@github.com> 
Envoyé : mardi 14 août 2018 10:51
À : GeotrekCE/Geotrek-rando <Geotrek-rando@noreply.github.com>
Cc : DELOUSTAL <pierre.deloustal@wanadoo.fr>; Author <author@noreply.github.com>
Objet : Re: [GeotrekCE/Geotrek-rando] Problème à l’exécution du script Gulp dans la commande npm run dist (#661)

 

Remarque : dans la doc d'installation de Geotrek-rando , j'ai rencontré plusieurs erreurs

Quelle doc et quelles erreurs ? Comme l'a dit Camille, concernant l'installation de nodejs, la doc de référence est https://github.com/GeotrekCE/Geotrek-rando/blob/master/docs/install-node.md et indique donc de télécharger https://deb.nodesource.com/setup_6.x (6.x) et non https://deb.nodesource.com/setup_6.14.1 (6.14.1).

Le fichier .nvmrc indique effectivement 6.14.1 mais, en principe, c'est le numéro majeur (le plus à gauche) qui compte pour la compatibilité. Aucune chance que Geotrek-rando fonctionne avec node 8.x. Par contre, il n'y a pas de raison que ça ne fonctionne pas avec la dernière version 6.x, à savoir la 6.14.3.

**Comment by camillemonchicourt** [comment]
OK donc cela est du au fait que Ubuntu 18 est livré avec NodeJS version 8. Hors Geotrek-rando n'a pas encore été migré en version 8 mais nécessite une version 6 de Node JS pour le moment. 

Méthode fournie par @gutard pour faire fonctionner Geotrek-rando avec Ubuntu 18.04 : 

Pour fonctionner en Ubuntu 18.04, une solution possible est d'utiliser ``nvm`` :

```
apt-get remove nodejs
rm -rf node_modules
wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
```

Fermer et rouvrir le terminal.

```
nvm install
nvm use
npm install
npm run dist
```

La commande (``nvm use``) sera à relancer à chaque nouvelle ouverture du terminal.
La suppression du répertoire ``node_modules`` est nécessaire lorsqu'on change de version de nodejs.
