### ISSUE TITLE
Near objects not displayed on map

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-rando#688]
Not sure on which it is and if it is only on the new UX version, but NEAR OBJECTS are not displayed on map on trek detail pages : http://rando.marittimemercantour.eu/itineraire/anello-delle-vene-del-tanaro/

**Comment by camillemonchicourt** [comment]
It is working when you go direct to the detail page (from a link or with refreshing but not when you come from the Search page.

**Comment by camillemonchicourt** [comment]
The problem is not only on the UX version. 
Also on the classic version. 
Example : http://www.rando-alpes-haute-provence.fr/randonnee-trail/actualite-la-rando-du-mois/

**Comment by camillemonchicourt** [comment]
De la même manière, quand on est sur la fiche d'une itinérance et que l'on affiche les étapes, celles-ci n'apparaissent plus sur la carte du séjour. 

Exemple : http://rando.marittimemercantour.eu/itinerance/alta-via-dei-re/

**Comment by camillemonchicourt** [comment]
Fix en cours : https://github.com/GeotrekCE/Geotrek-rando/pull/719

**Comment by camillemonchicourt** [comment]
Du coup c'est corrigé dans la version 2.21.1-ux mais pas dans 2.21.1 ?

**Comment by gutard** [comment]
Cf. https://github.com/GeotrekCE/Geotrek-rando/pull/721#issuecomment-531259380_

**Comment by camillemonchicourt** [comment]
Aussi fixé sur la version normale 2.21.2 : https://github.com/GeotrekCE/Geotrek-rando/releases

**Comment by amandine-sahl** [comment]
Après avoir installé la version 2.21.2, sauf erreur de ma part, je ne constate aucun changement, les objets "à proximité" ne s'affichent toujours pas.

**Comment by camillemonchicourt** [comment]
En effet.

**Comment by samuelpriou** [comment]
A contrario cela fonctionne pour [https://github.com/GeotrekCE/Geotrek-rando/releases/tag/2.21.2-ux](url)

**Comment by numahell** [comment]
Normalement corrigé depuis la 2.21.3 par la PR #726, c'était ok pour les POIs mais pas pour les éléments à proximité.

**Comment by camillemonchicourt** [comment]
En effet, corrigé dans les versions récentes (testé sur 2.26.0)
