### ISSUE TITLE
Problème upgrade 2.26.0

### ISSUE THREAD

**Issue by alizeelamarque** [GeotrekCE/Geotrek-rando#691]
Bonjour,

Je remplace Thomas durant son absence au PNR du Haut-Jura.

J'ai effectué les mises à jour jusqu'à la 2.25.3 sans soucis mais à la 2.26.0 j'obtiens l'erreur "Could not update data !".
J'ai regardé dans les logs d'installation et j'ai le message suivant : 

`File "/home/adminsig/Geotrek-admin-2.26.1/lib/eggs/Django-1.11.14-py2.7.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "touristiccontenttype_id" does not exist
`

J'ai pu redémarrer sur la 2.25.3 qui semble fonctionnelle.

Quelqu'un d'autre a eu ce soucis et sait comment le résoudre ?

Merci.

Alizée

**Comment by Cynthia-Borot-PNE** [comment]
Bonjour,
J'ai eu la même erreur que toi lors de l'upgrade de l'instance du PN des Ecrins en début de semaine.
Par manque de temps n'ai pas poussé plus loin. Je suis donc aussi retournée sur la 2.25.3.

**Comment by samuelpriou** [comment]
Il s'agit de Geotrek-admin et non pas Geotrek-rando.
A++

**Comment by alizeelamarque** [comment]
Oups, effectivement !
Je recrée une issue sur Geotrek-admin et ferme celle-là ? ^^

**Comment by camillemonchicourt** [comment]
Oui à fermer et rouvrir sur le dépôt Geotrek-admin
