### ISSUE TITLE
Erreur lors de mise à jour Geotrek-rando-2.20.0-ux3

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-rando#696]
Nouvelle installation : geotrek-rando-2.20.0-ux3
Ancienne version : Geotrek-rando-2.19.1

Lors de ma première tentative, après avoir lancé la commande npm install, il est resté bloqué sur une ligne pendant toute un nuit (voir image).

Ce matin, je suppose que c'est ma version de node.js qui n'est pas  jour et je la mets à jour,passant d'une version 6.x.x à la 12.3.0.

Je retente l'installation et il me sort cette erreur : 

/home/rando65gav/.node-gyp/12.3.0/include/node/node.h:107:24: fatal error: util-inl.h: No such file or directory

J'ai mis les logs en pj. Pourrais-t-on m 'expliquer ce que j'ai raté dans ma démarche s'il vous plaît ? (J'ai suivi la doc pour faire l'upgrade).

![bug_installation_Geotrek-rando-2 20 0-ux3](https://user-images.githubusercontent.com/45095227/58166329-e1131a00-7c89-11e9-8571-b1b14db5c6ea.png)
[2019-05-22T09_49_11_294Z-debug.log](https://github.com/GeotrekCE/Geotrek-rando/files/3206842/2019-05-22T09_49_11_294Z-debug.log)

**Comment by camillemonchicourt** [comment]
Il n'est pas indiqué de passer à Node JS 12. 
A ma connaissance, Geotrek-rando est compatible avec la version 6 et ce fichier l'indique : https://github.com/GeotrekCE/Geotrek-rando/blob/master/.nvmrc
Ainsi que la documentation : https://github.com/GeotrekCE/Geotrek-rando/blob/master/docs/install-node.md

**Comment by gutard** [comment]
Geotrek-rando est effectivement validé avec la version enregistrée dans le fichier .nvmrc (actuellement v6.14.3). Ça ne veut pas dire que ça ne marche pas avec d'autres versions, mais il n'y a aucune garantie.

En cas de changement de version de npm il est conseillé de supprimer le répertoire node_modules/ et de relancer npm install.

**Comment by gutard** [comment]
Geotrek-rando est effectivement validé avec la version enregistrée dans le fichier .nvmrc (actuellement v6.14.3). Ça ne veut pas dire que ça ne marche pas avec d'autres versions, mais il n'y a aucune garantie.

En cas de changement de version de npm il est conseillé de supprimer le répertoire node_modules/ et de relancer npm install.

**Comment by gutard** [comment]
> il est resté bloqué sur une ligne pendant toute un nuit (voir image)

Ça ressemble à un problème de firewall. Je suppose que le port 80 (http) sortant est ouvert. Qu'en est-il des ports 443 (https) et 9418 (git) potentiellement utilisés par npm install ?

**Comment by mviadere-openig** [comment]
Je ne sais pas si c'est la meilleure méthode, mais j'ai vérifié avec ce site : [](https://www.yougetsignal.com/tools/open-ports/)
Il me dit que les deux ports en questions sont fermés. 
Donc si je comprends bien : 
 - je dois repasser node.js en v6.14.3 (sachant que la manipulation de suppression du repertoire node_modules/ n'a pas fonctionné)
- ouvrir les ports et relancer un npm install ?

**Comment by mviadere-openig** [comment]
J'ai fait les manipulations décrites plus haut. Pour repasser à l'ancienne version j'ai utilisé nvm puis j'ai ouvert les ports, l'installation a pu se terminer, c'était bien ça qui bloquait. Merci encore Gaël.

**Comment by camillemonchicourt** [comment]
OK donc il fallait bien rester sur Node JS 6. 
Le problème venait donc de ports non ouverts.
