### ISSUE TITLE
Version multilingue - Pages statistiques

### ISSUE THREAD

**Issue by alizeelamarque** [GeotrekCE/Geotrek-rando#702]
Bonjour,

Après le passage en anglais de Geonature, on observe un bug sur la liste des pages statistiques.
En français, aucun souci, mais en anglais le fonctionnement est dégradé.
Le "En savoir plus" est bien traduit en "About us" mais le contenu de la liste n'est pas traduit et les liens de redirection sont incorrects et ne fonctionnent pas (sauf lien vers site externe) :
![bug_pages_stats_geotrek](https://user-images.githubusercontent.com/49558245/59418644-a9e7e280-8dc9-11e9-9421-2e252cb17f74.PNG)

Par exemple, "Conseils aux randonneurs" est sensé mener à une page statique qui a été traduite. Mais au clic, il actualise la page de la carte.

Par contre en version française, on peut aller sur la page "Conseils en randonneurs".
Et si, sur cette même page, en repasse en anglais, la page est bien traduite.

**Comment by gutard** [comment]
Il y a effectivement des soucis lors du changement de langue. Cependant, si vous rechargez la page cela devrait être OK. Ou bien si le navigateur est configuré pour accepter l'anglais et pas le français, l'utilisateur devrait arriver directement sur la version anglais sans dysfonctionnement. Cependant, vous n'avez publié aucune page statique en anglais donc le menu est vide.

**Comment by alizeelamarque** [comment]
Pourtant sur Geotrek-Admin les pages sont publiées en français et en anglais...

**Comment by alizeelamarque** [comment]
Et j'ai cette erreur dans la console, uniquement pour la version anglaise :
`Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: flat in flatpages track by flat.slug, Duplicate key: transport, Duplicate value: {"id":14,"title":"Transport","external_url":"","content":"<div class=\"row\"><div class=\"column col-md-12 col-sm-12 col-xs-12\"><p>To visit and get about in the High-Jura, visit <a href=\"http://www.reshaut-jura.fr\" target=\"_blank\" data-mce-href=\"http://www.reshaut-jura.fr\">www.reshaut-jura.fr</a>, the eco-mobility portal listing all means of transport within the Park. <br></p><p><input name=\"mce_0\" value=\"<p>Pour venir et vous d&amp;eacute;placer dans le Haut-Jura, consultez <a href=&quot;http://www.reshaut-jura.fr&quot; target=&quot;_blank&quot;>www.reshaut-jura.fr</a>, le portail de l&amp;rsquo;&amp;eacute;co mobilit&amp;eacute; qui recense l&amp;rsquo;ensemble des moyens de locomotion sur le territoire du Parc</p>\" type=\"hidden\"></p><input name=\"mce_0\" type=\"hidden\"></div></div>","target":"mobile","last_modified":"2019-05-10T11:34:04.496645Z","slug":"transport","media":[],"source":[],"portal":[],"published":true,"published_status":[{"lang":"en","status":true,"language":"English"},{"lang":"fr","status":true,"language":"French"}],"publication_date":"2018-02-09"}
http://errors.angularjs.org/1.4.9/ngRepeat/dupes?p0=flat%20in%20flatpages%20track%20by%20flat.slug&p1=transport&p2=%7B%22id%22%3A14%2C%22title%22%3A%22Transport%22%2C%22external_url%22%3A%22%22%2C%22content%22%3A%22%3Cdiv%20class%3D%5C%22row%5C%22%3E%3Cdiv%20class%3D%5C%22column%20col-md-12%20col-sm-12%20col-xs-12%5C%22%3E%3C!--gm-editable-region--%3E%3Cp%3ETo%20visit%20and%20get%20about%20in%20the%20High-Jura%2C%20visit%20%3Ca%20href%3D%5C%22http%3A%2F%2Fwww.reshaut-jura.fr%5C%22%20target%3D%5C%22_blank%5C%22%20data-mce-href%3D%5C%22http%3A%2F%2Fwww.reshaut-jura.fr%5C%22%3Ewww.reshaut-jura.fr%3C%2Fa%3E%2C%20the%20eco-mobility%20portal%20listing%20all%20means%20of%20transport%20within%20the%20Park.%20%3Cbr%3E%3C%2Fp%3E%3Cp%3E%3Cinput%20name%3D%5C%22mce_0%5C%22%20value%3D%5C%22%3Cp%3EPour%20venir%20et%20vous%20d%26amp%3Beacute%3Bplacer%20dans%20le%20Haut-Jura%2C%20consultez%20%3Ca%20href%3D%26quot%3Bhttp%3A%2F%2Fwww.reshaut-jura.fr%26quot%3B%20target%3D%26quot%3B_blank%26quot%3B%3Ewww.reshaut-jura.fr%3C%2Fa%3E%2C%20le%20portail%20de%20l%26amp%3Brsquo%3B%26amp%3Beacute%3Bco%20mobilit%26amp%3Beacute%3B%20qui%20recense%20l%26amp%3Brsquo%3Bensemble%20des%20moyens%20de%20locomotion%20sur%20le%20territoire%20du%20Parc%3C%2Fp%3E%5C%22%20type%3D%5C%22hidden%5C%22%3E%3C%2Fp%3E%3Cinput%20name%3D%5C%22mce_0%5C%22%20type%3D%5C%22hidden%5C%22%3E%3C!--%2Fgm-editable-region--%3E%3C%2Fdiv%3E%3C%2Fdiv%3E%22%2C%22target%22%3A%22mobile%22%2C%22last_modified%22%3A%222019-05-10T11%3A34%3A04.496645Z%22%2C%22slug%22%3A%22transport%22%2C%22media%22%3A%5B%5D%2C%22source%22%3A%5B%5D%2C%22portal%22%3A%5B%5D%2C%22published%22%3Atrue%2C%22published_status%22%3A%5B%7B%22lang%22%3A%22en%22%2C%22status%22%3Atrue%2C%22language%22%3A%22English%22%7D%2C%7B%22lang%22%3A%22fr%22%2C%22status%22%3Atrue%2C%22language%22%3A%22French%22%7D%5D%2C%22publication_date%22%3A%222018-02-09%22%7D
minErr/<@http://randonature.parc-haut-jura.fr/dist/scripts/rando.js:124:681
compile/</<@http://randonature.parc-haut-jura.fr/dist/scripts/rando.js:124:257906
$watchCollection/<@http://randonature.parc-haut-jura.fr/dist/scripts/rando.js:124:124476
$digest@http://randonature.parc-haut-jura.fr/dist/scripts/rando.js:124:125717
$apply@http://randonature.parc-haut-jura.fr/dist/scripts/rando.js:124:127793
sendReq/<@http://randonature.parc-haut-jura.fr/dist/scripts/rando.js:124:85166
completeRequest@http://randonature.parc-haut-jura.fr/dist/scripts/rando.js:124:87597
createHttpBackend/</xhr.onload@http://randonature.parc-haut-jura.fr/dist/scripts/rando.js:124:88529`

**Comment by gutard** [comment]
> Duplicate key: transport

Il y a deux pages avec le même titre "Transport". C'est cela qui cause un souci.

**Comment by alizeelamarque** [comment]
Super ça fonctionne, merci !
