### ISSUE TITLE
Question : affichage des pages statiques

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-rando#705]
Geotrek-admin : 2.27.1
Geotrek-rando : 2.20.0-ux3

Bonjour, est-ce qu'il  y a une manipulation technique supplémentaire pour afficher le menu "en savoir plus" sur le header du Geotrek-Rando qui permet d'avoir le sous-menu avec les pages statiques ? Pour l'un de mes adhérents, malgré les avoir rempli et coché la case "Publié", rien ne s'affiche.

Exemple : 
![exemple](https://user-images.githubusercontent.com/45095227/60161997-e6b7ce80-97f8-11e9-9a72-0a6f8684d0f9.png)

**Comment by camillemonchicourt** [comment]
Pas sur de comprendre ?
Ici le menu EN SAVOIR PLUS est bien affiché.
Quel est le problème ?

**Comment by mviadere-openig** [comment]
Sur la version que je suis en train de customiser, il n'est pas affiché.

Lien ( c'est en cours de customisation ) : http://www.randovalleesdegavarnie.com/?categories=T4

Un autre exemple avec le Geotrek Rando du Gard , qui eux aussi n'ont pas ce menu : https://gardpleinenature.gard.fr/?categories=E&categories=T1&categories=T2&categories=T4&categories=T5

Dans le custom-header.html il a bien pourtant une balise flat-menu.

**Comment by camillemonchicourt** [comment]
En effet tu n'as aucune page statique : http://www.randovalleesdegavarnie.com/api/fr/flatpages.geojson
Donc le menu EN SAVOIR PLUS ne s'affiche pas dans ton Geotrek-rando.
Idem pour le CD30 qui ne doit pas en avoir pour le moment : https://gardpleinenature.gard.fr/api/fr/flatpages.geojson

Il faut en effet uniquement Publier les pages statiques, puis relancer une synchro et bien les copier sur le serveur Geotrek-rando.

Donc il faut que tu creuses ton problème au niveau du contenu de ton Geotrek-admin et/ou de ta synchro.

**Comment by mviadere-openig** [comment]
Merci pour les précisions.
Peux-tu me dire leur répertoire d'emplacement sur l'admin et celui où l'on doit les copier s'il te plait ?

**Comment by camillemonchicourt** [comment]
Ce n'est pas différent de la synchronisation des autres données (randos, POI...).
Les json sont générés par la commande ``sync_rando`` dans le répertoire ``data`` de Geotrek-admin (``data/api/fr/flatpages.geojson`` en l'occurrence) puis ce répertoire ``data``est copié ou accédé par Geotrek-rando.

**Comment by mviadere-openig** [comment]
Bonjour, merci pour ces précisions, le problème est résolu.
