### ISSUE TITLE
Question : comment afficher un menu latéral plutôt qu'un menu horizontale

### ISSUE THREAD

**Issue by GuillaumeBoitel** [GeotrekCE/Geotrek-rando#706]
Je suis sous Geotrek-Rando 2.20.0 et j'ai une barre de menu horizontale (comme sur le site du Parc du Mercantour : http://rando.marittimemercantour.eu/?categories=T).

Je souhaiterais plutôt avoir une barre de menu verticale (comme sur le site du Grand Tour des Ecrins : http://www.grand-tour-ecrins.fr/?categories=T7).

J'ai regardé dans le repértoire custom du GTE (https://geotrek.ecrins-parcnational.fr/ressources/technique/custom/PN-Ecrins-GTE/) mais je ne vois dans aucun de templates une référence à cette barre.

**Comment by camillemonchicourt** [comment]
Je ne comprends, tu parles du menu "En savoir plus" qui liste les pages statiques ? 
Si c'est celui-ci, alors c'est de la surcouche du Header, voir les exemple (https://geotrek.ecrins-parcnational.fr/ressources/technique/custom/)

Ou tu parles du menu des catégories de contenus ? 
Dans ce cas, la version horizontale au PNM correspond à Geotrek-rando-x.y.z-ux
La version classique (verticale comme sur GTE) est la version Geotrek-rando-x.y.z

Tu as du installer la version 2.20.0-ux3.

Le travail de refonte ergonomique a apporté des améliorations, mais n'est pas abouti, c'est pour ça qu'on a gardé les 2 versions en parallèle pour le moment, mais il va falloir qu'on donne suite à cela. 

Des précisions ici : https://groups.google.com/forum/#!topic/geotrek-fr/op8DtMRFZ_E

**Comment by GuillaumeBoitel** [comment]
Oui c'est bien le menu des catégories de contenus.
Effectivement j'ai installé la version ux3. Donc si je comprends bien, je ne peux pas avoir la main par les css et les templates sur la barre de menu de contenu ? Il faut donc que je change de version de geotrek ?

**Comment by camillemonchicourt** [comment]
Ce sont des versions très différentes au niveau de toute la construction du menu des CATEGORIES et des FILTRES. Donc une surcouche ne suffit pas pour passer du menu horizontal à un menu vertical. Aperçu des évolutions : https://github.com/GeotrekCE/Geotrek-rando/compare/2.20.0...2.20.0-ux3

Sinon en dehors de cela, tu peux bien sur surcoucher le CSS de Geotrek-rando pour ajuster le style des menus comme de tout le reste.
