### ISSUE TITLE
Question : comment afficher les catégories "A pied", "VTT", etc plutôt que "Randonnée"

### ISSUE THREAD

**Issue by GuillaumeBoitel** [GeotrekCE/Geotrek-rando#707]
Dans le menu latéral, comment peut on afficher les pratiques (Vélo, VTT, A pied...) plutôt que l'ensemble des randonnées ?

J'ai essayé de regarder les options disponibles dans le setting.custom.json (https://github.com/GeotrekCE/Geotrek-rando/blob/master/docs/settings-custom-json-all-options.md), mais je n'ai pas vu d'options adéquate.

**Comment by camillemonchicourt** [comment]
Cet éclatement de fait au niveau des fichiers de la synchro donc le paramétrage est au niveau de Geotrek-admin. 
Un paramètre du genre Split by categories dans la conf avancée

**Comment by gutard** [comment]
C'est ça, il faut mettre `SPLIT_TREKS_CATEGORIES_BY_PRACTICE = True` dans `geotrek/settings/custom.py`

**Comment by GuillaumeBoitel** [comment]
Ok, merci.
