### ISSUE TITLE
Question : comment activer les filtres sur les contenus touristique dans la barre latérale

### ISSUE THREAD

**Issue by GuillaumeBoitel** [GeotrekCE/Geotrek-rando#708]
Dans le menu latérale, je souhaiterais pouvoir afficher les filtres relatifs à chaque type de contenu touristique (comme ce qui se fait par exemple sur le site du [Grand Tour des écrins ](http://www.grand-tour-ecrins.fr/?categories=C1&categories=C6&categories=T4&categories=T7&categories=T8)).

J'ai uniquement une flèche à côté d'itinéraire qui me permet d'accéder au filtre des itinéraires, mais je n'ai pas de flèches me permettant de faire la même chose à côté de chaque type de contenu touristique.

**Comment by camillemonchicourt** [comment]
Peux-tu ajouter une capture écran pour illustrer cela ?
Je ne vois pas bien de quoi il s'agit.

**Comment by GuillaumeBoitel** [comment]
Voici deux capture : 
- la première montre le menu latéral avec les flèches sur le site des Ecrins :
![Capture0](https://user-images.githubusercontent.com/48252187/60444821-3d207500-9c1e-11e9-80f6-5bc1bf9bc5f5.PNG)
- la seconde montre le menu latéral avec le filtre (toujours sur le site des Ecrins) :
![Capture1](https://user-images.githubusercontent.com/48252187/60444822-3db90b80-9c1e-11e9-9380-440649b9cbc4.PNG)
- La dernièrne montre le menu latéral au PNPC sans les flèches (donc impossible d'ouvrir la partie filtre) :
![Capture2](https://user-images.githubusercontent.com/48252187/60444992-97213a80-9c1e-11e9-8848-246bbe9a5482.PNG)

**Comment by camillemonchicourt** [comment]
Il doit y avoir une erreur quelque part, car cela se fait normalement tout seul.
Des messages d'erreur dans la console ?

**Comment by GuillaumeBoitel** [comment]
Non pas d'erreur dans la console. Peut-être un conflit de style... Je vais repasser mon css au peigne fin !

**Comment by gutard** [comment]
Il n'y a peut être aucun filtre à afficher. La flèche ne s'affiche que si il y a un filtre.

**Comment by gutard** [comment]
Au final, quel était le problème ?

**Comment by GuillaumeBoitel** [comment]
Effectivement il n'y avait pas de filtre à afficher. Le contenu touristique provenait d'APIDAE mais les personnes qui les ont remplis n'ont pas renseignés de type et de type d'usage, donc pas possibilité de filtrer. J'avais juste regardé dans les listes de valeurs et non dans les données elles mêmes ce qui m'avait induit en erreur.
