### ISSUE TITLE
Question : Où peut on changer le titre de l'onglet de la page principale de geotrek-rando ?

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-rando#710]
Bonjour, j'aimerai changer le titre de l'onglet de la page du geotrek-rando, dans quel fichier doit-on se rendre pour faire la modification ? 
![onglet_titre](https://user-images.githubusercontent.com/45095227/60878153-7a4cbe80-a23f-11e9-875b-ad688ffc2aa7.png)

**Comment by camillemonchicourt** [comment]
La surcouche des balises <title> et <description> sont à faire dans les fichiers de langue : https://github.com/GeotrekCE/Geotrek-rando/blob/master/docs/settings.md#translations

**Comment by mviadere-openig** [comment]
merci Camille !
