### ISSUE TITLE
Les points des contenus "A proximité" ne s'affichent plus sur la carte

### ISSUE THREAD

**Issue by amandine-sahl** [GeotrekCE/Geotrek-rando#717]
Suite à une migration vers geotrek-rando 2.21.0, les contenus de la rubrique "a proximité" ne semblent plus s'afficher sur la carte.

**Version 2.19.3**
![image](https://user-images.githubusercontent.com/3088650/64021311-f07ceb80-cb33-11e9-8f39-180101db7de0.png)

**Version 2.21.0**
![image](https://user-images.githubusercontent.com/3088650/64021263-d3e0b380-cb33-11e9-9e32-939db6fbedbd.png)

**Comment by camillemonchicourt** [comment]
Oui, identifié ici : https://github.com/GeotrekCE/Geotrek-rando/issues/688
Duplicate.
