### ISSUE TITLE
Problème de message lors d'un signalement sur un itinéraire.

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-rando#731]
Geotrek-admin : 2.29.2
Geotrek-rando : 2.20.0-ux3

Lorsqu'un utilisateur fait un signalement sur un itinéraire, il reçoit comme message ceci : 

"Le message n'a pu être enregistré. Veuillez nous excuser pour ce désagrément. Nos équipes ont été prévenues et analysent le problème."

Pourtant, le signalement est bien visible sur l'onglet signalement du Geotrek-admin.

Dans src/app/translation/po/fr.po j'ai ceci : 

`msgid "SUCCESS_WARNING"
msgstr "Le message a bien été enregistré. Merci pour votre aide !"

msgid "ERROR_WARNING"
msgstr "Le message n'a pu être enregistré. Veuillez nous excuser pour ce désagrément. Nos équipes ont été prévenues et analysent le problème."
`
je l'ai copié/coller dans Geotrek-rando/custom/po/fr.po

puis fait un npm run dist, mais aucun changement n'est pris en compte.

j'ai tenté de changer le msgid "ERROR_WARNING" en lui mettant le comme msgstr "Le message a bien été enregistré. Merci pour votre aide !"

Cela n'a pas fonctionné non plus. Quelle est la bonne manipulation requise ? 

Merci à vous.

**Comment by camillemonchicourt** [comment]
Je ne comprends pas pourquoi tu veux modifier le texte du message d'erreur. 
Il faut plutôt voir pourquoi c'est le message d'erreur qui est renvoyé, plutôt que de vouloir modifier le message d'erreur.

**Comment by mviadere-openig** [comment]
Parce que ce n'est pas dans mes compétences, je cherchais juste une alternative avant de poster sur Github.

**Comment by camillemonchicourt** [comment]
OK mais là tu as une erreur, il vaut mieux l'identifier que la contourner je pense.

**Comment by gutard** [comment]
As-tu configurer le settings suivant dans etc/settings/.ini ?
```
[nginx-conf]
# cors = domain.name.of.geotrek-rando.com
```
Cf. https://developer.mozilla.org/fr/docs/Web/HTTP/CORS

**Comment by gutard** [comment]
Il faut bien évidemment enlever le `#` en début de ligne sinon c'est un commentaire qui n'est pas pris en compte

**Comment by mviadere-openig** [comment]
voici ce qu'il y a dans  le settings.ini :
[nginx-conf]
server_name = siglr-geotrek-pnrgca.ataraxie.fr
cors = http://rando.parc-grands-causses.fr
real_ip = xx.xxx.xxx.xxx (j'ai caché l'adresse ip)
Sachant que l'adresse actuel est https://rando.parc-grands-causses.fr, cela ne viendrait pas de là ?

**Comment by mviadere-openig** [comment]
Après avoir consulté de la doc sur nginx et les conseils de Gaël Utard, voici la démarche détaillée pour résoudre le problème :

 - Dans /etc/nginx/sites-enabled/geotrek, il faut mettre la ligne add_header 'Access-Control-Allow-Origin' 'your.domain.name.of.geotrek';
Cela permet à régler le problème de cors, suite à ça on peut lancer un sudo nginx -t pour vérifier que que la syntaxe de nginx est ok.

 - on peut ensuite faire un sudo service nginx reload, ce qui permet de ne pas avoir à relancer un ./install.sh  qui pourrait casser la configuration SSL qu'on devrait reparamétrer ensuite (si le site est en https)

- J'ai trouvé ce lien [https://www.agix.com.au/enable-cors-with-nginx/](url) qui explique un peut mieux comment configurer le cors sous nginx( avec d'autres options possibles) et le tester en ligne de commande directement sous Linux.

Mon erreur venait d'une coquille dans le paramétrage du fichier situé dans Geotrek-rando/custom/settings.custom.json
Je me suis rappelé que le parametre "BACKOFFICE_URL": permet d'envoyer les formulaires de signalements.

Pour me rendre compte de mon erreur, j'ai vérifié la méthode POST dans la console de firefox dans l'onglet réseau pour me rendre compte que le nom de domaine qui bloquait le POST n'était pas le bon. 

En espérant que ça puisse servir.

**Comment by camillemonchicourt** [comment]
Depuis la version 2.33 de Geotrek-admin, il n'y a plus de fichier de configuration etc/settings.ini. 
L'URL du Geotrek-rando est demandée en console lors de l'installation ou lors de l’exécution de la commande de mise à jour de la configuration de base ``sudo dpkg-reconfigure geotrek-admin``.

Pour les autres paramètres de surcouche de NGINX, il faut les renseigner dans un nouveau fichier dédié. Voir https://github.com/GeotrekCE/Geotrek-admin/issues/1878 et la documentation : https://geotrek.readthedocs.io/en/master/configuration.html#nginx-configuration
