### ISSUE TITLE
Filtre de durée sur les contenus touristiques

### ISSUE THREAD

**Issue by eprouteau** [GeotrekCE/Geotrek-rando#733]
Bonjour,

Sur le portail public, j'ai une option de filtre de durée sur mes contenus touristiques alors que cette informations n'est pas présente lors de la saisie. Est-ce une option dans un fichier custom ?
Je suis en version 2.29.12 de geotrek-admin

Cordialement,

![2019-10-29 17_36_57-Geotrek Rando](https://user-images.githubusercontent.com/1401902/67788508-c2a01e80-fa72-11e9-9074-7bcdb06d8beb.png)

**Comment by camillemonchicourt** [comment]
Bonsoir, j'ai transféré votre ticket dans le dépôt Geotrek-rando car il se réfère plutôt à cet outil.
Quelle version de Geotrek-rando utilisez-vous ?
Son URL est publique ?

En tout cas, ce n'est pas normal car il n'y a pas d'information de durée dans les contenus touristiques, donc il n'y a pas de raison qu'ils aient un filtre de durée. 
Peut-etre un bug sur une version récente car je n'avais pas vu ça préalablement.

Le filtre DUREE ne s'applique que pour les randonnées. 

Voir toutes les options customisables de Geotrek-rando : https://github.com/GeotrekCE/Geotrek-rando/blob/master/docs/settings-custom-json-all-options.md

**Comment by eprouteau** [comment]
J'utilise la dernière version 2.21.4 (Non UX) Par contre l'URL n'est pas encore public mais j'ai observé le même comportement sur le parc des Cévennes : http://destination.cevennes-parcnational.fr/?categories=C1&categories=C2&categories=C5&categories=C6&categories=C7&categories=C8&categories=E&categories=T1&categories=T3&categories=T4

**Comment by camillemonchicourt** [comment]
OK alors cela semble être un problème apparu dans les versions récentes.
