### ISSUE TITLE
Panneau pois non ouverts sur la page détail

### ISSUE THREAD

**Issue by pnrma** [GeotrekCE/Geotrek-rando#746]
Geotrek-rando version 2.22.1

Page détail, le panneau à droite "Patrimoine" présentant les POIS à proximité n'est pas ouvert, malgré le paramétrage du paramètre `DEFAULT_INTEREST` avec comme valeur `pois` dans le fichier settings.custom.json.

Dernière version où ce paramètre est bien pris en compte : 2.20.0 (problème de prise en compte du paramètre `POI_EXPANDED` néanmoins).

**Comment by numahell** [comment]
Bonjour, nous avons corrigé plusieurs problèmes sur le panneau latéral de la page détail pour la version 2.25.0, il est possible qu'une mise à jour corrige le problème des POIS non dépliés. À la mise à jour, lancez `npm install` avant `npm run dist`, car certains packages ont été mis à jour.

**Comment by camillemonchicourt** [comment]
OK super, à tester/confirmer.
Aussi lié à https://github.com/GeotrekCE/Geotrek-rando/issues/688 ?

**Comment by numahell** [comment]
Pour préciser, le problème réglé par la 2.25.0 est le fait qu'un des panneaux dans la barre latérale n'était pas déplié alors qu'il devrait l'être.

Par contre le problème soulevé par #688 est un autre problème qui a été corrigé depuis la 2.21.3 par la PR #726.

**Comment by pnrma** [comment]
Testé et ok sur la version 2.26.1
