### ISSUE TITLE
Fiche itinéraire : Bug d'affichage des markers sur la carte pour les contenus à proximité

### ISSUE THREAD

**Issue by pnrma** [GeotrekCE/Geotrek-rando#750]
Lorsque l'on accède à une fiche itinéraire depuis la carte générale, les markers des contenus "à proximité" ne s'affichent pas sur la carte.
Lorsqu'il y a des POI, les markers pour les POI sont bien affichés mais lorsqu'on ouvre le panneau des contenus "à proximité", les markers correspondant à ces derniers ne s'affichent pas.

En revanche, cela fonctionne normalement lorsqu'on recharge la page.

Testé sur windows 10 avec firefox 74.0 et chrome 80.0

Version de Geotrek-rando : testé sur les versions 2.19.6 et 2.23.0

**Comment by camillemonchicourt** [comment]
A priori déjà identifié ici : https://github.com/GeotrekCE/Geotrek-rando/issues/688

**Comment by pnrma** [comment]
The original message was received at Mon, 30 Mar 2020 12:44:55 +0200
from vsmtp17.inforoutes.fr [46.18.231.70]

   ----- The following addresses had permanent fatal errors -----
<jferreira@alia8.inforoutes.fr>
    (reason: 550 Host unknown)

   ----- Transcript of session follows -----
550 5.1.2 <jferreira@alia8.inforoutes.fr>... Host unknown (Name server: alia8.inforoutes.fr: host not found)

**Comment by camillemonchicourt** [comment]
A priori le fix n'a pas corrigé le problème. 
Mais ticket existant ici : https://github.com/GeotrekCE/Geotrek-rando/issues/688
Je ferme donc cette issue.

**Comment by pnrma** [comment]
The original message was received at Thu, 11 Jun 2020 13:17:13 +0200
from vsmtp17.inforoutes.fr [46.18.231.70]

   ----- The following addresses had permanent fatal errors -----
<jferreira@alia8.inforoutes.fr>
    (reason: 550 Host unknown)

   ----- Transcript of session follows -----
550 5.1.2 <jferreira@alia8.inforoutes.fr>... Host unknown (Name server: alia8.inforoutes.fr: host not found)

**Comment by pnrma** [comment]
The original message was received at Thu, 11 Jun 2020 13:17:14 +0200
from vsmtp16.inforoutes.fr [46.18.231.66]

   ----- The following addresses had permanent fatal errors -----
<jferreira@alia8.inforoutes.fr>
    (reason: 550 Host unknown)

   ----- Transcript of session follows -----
550 5.1.2 <jferreira@alia8.inforoutes.fr>... Host unknown (Name server: alia8.inforoutes.fr: host not found)
