### ISSUE TITLE
Ubuntu

### ISSUE THREAD

**Issue by thomaspnrhj** [GeotrekCE/Geotrek-rando#752]
Dans les prérequis d’installation il est marqué qu'il faut un serveur avec Ubuntu 14.04. 
Cette version devient de plus en plus rare dans les offres de VPS, est que ça fonctionne malgré tout en 16.04 ou 18.04 ?
Merci d'avance,
Thomas

**Comment by gutard** [comment]
C'est une vieillerie. je viens de corriger la doc. Il est au contraire recommandé d'utiliser la dernière version LTS. Le seul souci se situe au niveau de la version de nodejs. Il est donc recommandé d'installer [nvm](https://github.com/nvm-sh/nvm).

**Comment by thomaspnrhj** [comment]
Merci pour ta réponse !
