### ISSUE TITLE
Problème installation 2.24.0

### ISSUE THREAD

**Issue by thomaspnrhj** [GeotrekCE/Geotrek-rando#755]
Lors de installation, j'ai le message d'erreur suivant : 
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.13
J'ai oublié d'installer une dépendance ? Quelqu'un peut m'aider ?
Merci,
Thomas

**Comment by gutard** [comment]
C'est juste un avertissement. Tu peux l'ignorer.

**Comment by thomaspnrhj** [comment]
Ok, merci de ton retour

Le 26 mai 2020 20:06, Gaël UTARD <notifications@github.com> a écrit :

C'est juste un avertissement. Tu peux l'ignorer.
