### ISSUE TITLE
Problème publication itinéraires

### ISSUE THREAD

**Issue by PierreLABADIE** [GeotrekCE/Geotrek-rando#757]
Bonjour à tou·te·s,
Nous faisons face avec un partenaire à un souci de publication d'une rando :
Dans l'admin (Version 2.33.11), ses itinéraires sont bien saisis en mode publié avec en portail cible l'URL du portail rando-champagne-ardenne.com (http://rando-champagne-ardenne.com)
Ses itinéraires ne sont pourtant pas publiés.

Ils sont renseignés avec des itinéraires liés (et non pas enfants qui masque les itinéraires). Est-ce que ça viendrait de ce paramétrage ?

Merci pour vos lumières ou à disposition pour plus de détails,
Pierre

**Comment by camillemonchicourt** [comment]
Quand on souhaite associer des contenus à un portail ou à un autre, il faut répercuter les filtres par portail dans les paramètres de synchronisation : https://geotrek.readthedocs.io/en/master/synchronization.html#synchronization-filtered-by-source-and-portal

Est-ce que cela a été fait ?
Peux-tu préciser ce qui a été fait, l'objectif et le problème ?

Les itinéraires liés sont juste une information qui n'a pas de conséquence sur la publication ou non.

**Comment by PierreLABADIE** [comment]
Je n'ai pas la main sur ce volet trop technique pour moi.
**L'objectif** : publier de nouveaux itinéraires sur le portail pour l'instant unique : www.rando-champagne-ardenne.com

**Ce qui a été fait :** 
Concrètement, il y a eu des migrations successives de l'admin jusqu'à la version actuelle.
En parallèle, nous (l'ART /ses partenaires) continuait à publier sans changer notre méthode.
J'ai simplement ajouté le paramètre "portail cible" depuis mon navigateur dans l'interface de l'Admin.

**Le problème :** 
Les nouveaux itinéraires ne sont pas publiés malgré le paramétrage dans l'admin depuis le navigateur.
Il doit donc y avoir un bout de code à modifier par Makina qui gère la maintenance pour nous si je comprends bien la ressource vers laquelle tu pointes, non ?

**Comment by camillemonchicourt** [comment]
OK merci pour ces précisions. 
Si tu as ajouté un portail cible sans le répercuter dans les paramètres de la synchronisation, alors celui-ci n'est pas pris en compte.
Mais si ta synchronisation se fait jusque là sans filtrer par portail, alors leurs itinéraires devraient continuer à remonter à la synchronisation.

En effet il faut voir comme test paramétrée ta synchronisation.

**Comment by gutard** [comment]
Il y a une configuration à faire au niveau de la synchronisation pour que celle-ci cible un portail particulier. Par défaut la synchronisation ne sélectionne que les éléments qui n'ont aucun portail spécifié.

**Comment by PierreLABADIE** [comment]
Merci Gael,
Par contre, les itinéraires créés dans un premier temps n'avaient pas de portail cible de renseigné et malgré tout ils n’apparaissaient pas.

Gael, je passe par l'adresse support pour faire une demande de maintenance et corriger ce souci alors ;)

**Comment by PierreLABADIE** [comment]
Problème résolu, merci !
