### ISSUE TITLE
Paramétrage Géotrek-rando 2.24.1

### ISSUE THREAD

**Issue by chanteclair12** [GeotrekCE/Geotrek-rando#761]
Re bonjour,
Le post #760 ayant été fermé avant que je n'ai pu répondre, j'en crée un nouveau évoquant ce petit problème de paramétrage.

> Subsiste un problème de paramétrage, sans doute bénin, qui fait qu'en saisissant l'Url du geotrek-rando, on ne tombe pas directement sur l'interface, mais sur une page intermédiaire avec 2 liens hypertexte ( Enter website Don't display this page anymore), le 1er permettant d'accéder au site.

Gutard :
> https://github.com/GeotrekCE/Geotrek-rando/blob/master/docs/settings-custom-json-all-options.md#main-options

> Il faut ajouter "SHOW_HOME": false dans custom/settings.custom.json

Ce paramètre est bien présent sur la valeur "False" dans le fichier settings.custom.json mais le chargement de la page est identique, qu'il soit sur False ou True.

**Comment by gutard** [comment]
Pour s'y retrouver il faut qu'on puisse distinguer ce qui a été réglé ou pas comme problème. D'où les bonnes pratiques de :
* créer un ticket différent pour chaque problème différent
* fermer le ticket quand le problème est réglé

Vous pouvez réouvrir un ticket fermé si vous pensez que le problème n'est pas réellement réglé.

**Comment by gutard** [comment]
Et du coup je remets la réponse que j'ai faite dans l'autre ticket avant de le fermer :

Avez-vous refait un build après la modification ?

https://github.com/GeotrekCE/Geotrek-rando/blob/master/docs/settings-custom-json-all-options.md#settingscustomjson

    To apply changes after editing settings, launch bundling task again with running npm run dist

**Comment by chanteclair12** [comment]
> 
> 
> Pour s'y retrouver il faut qu'on puisse distinguer ce qui a été réglé ou pas comme problème. D'où les bonnes pratiques de :
> 
>     * créer un ticket différent pour chaque problème différent
> 
>     * fermer le ticket quand le problème est réglé
> 
> 
> Vous pouvez réouvrir un ticket fermé si vous pensez que le problème n'est pas réellement réglé. Ou commenter un ticket fermé.

Ok pas de soucis.
Etant dans des problèmes d'installation, je considérais (à tort ou à raison) que cette question d'accès direct au site était dans la continuité de la thématique abordée dans ce post.

**Comment by chanteclair12** [comment]
> 
> 
> Et du coup je remets la réponse que j'ai faite dans l'autre ticket avant de le fermer :
> 
> Avez-vous refait un build après la modification ?
> 
> https://github.com/GeotrekCE/Geotrek-rando/blob/master/docs/settings-custom-json-all-options.md#settingscustomjson
> 
> ```
> To apply changes after editing settings, launch bundling task again with running npm run dist
> ```

C'est une ligne que je n'avais pas vu et qui résout mon problème, merci.
Je me permets d'ajouter 1 autre question relative au paramétrage : 
 - est-il possible de paramétrer l'étendue géographique sur laquelle le portail doit s'ouvrir (comme pour Geotrek-admin dans le settings.ini) ou est-ce lié aux données récupérées depuis le geotrek-admin ?
Merci.

**Comment by camillemonchicourt** [comment]
Oui bien sur que c'est possible. Dans les paramètres on peut définir le centrage de la carte et le zoom par défaut, comme indiqué dans la liste des paramètres : https://github.com/GeotrekCE/Geotrek-rando/blob/master/docs/settings-custom-json-all-options.md#leaflet-conf-options

**Comment by chanteclair12** [comment]
Merci beaucoup.
