### ISSUE TITLE
échelles de sélection pas directement visibles + borne du filtre pas directement positionnée

### ISSUE THREAD

**Issue by pierreloicq** [GeotrekCE/Geotrek-rando#773]
Sur la [plateforme du parc de la Vanoise](rando.vanoise.com), on a un comportement que je retrouve également sur les plateformes du [Gard](https://gardpleinenature.gard.fr/) et de [Serre-Ponçon](http://www.rando-serreponcon.com/?categories=T4) : les échelles de sélection ne sont pas directement visibles quand on ouvre la page (il faut cliquer sur le + pour les voir) et une des deux boules qui représente la borne du filtre n'est pas directement positionnée sur l'échelle (il faut cliquer pour ce faire). 
Si quelqu'un sait si ce comportement correspond à une version spécifique de GT-rando, cela m'intéresse.
La Vanoise est sur la version 2.16.2

Merci
Pierre Loicq (mission geotrek sept à déc 2020)

**Comment by gutard** [comment]
A tout hasard : option FILTERS_DEFAULT_OPEN ?

**Comment by pierreloicq** [comment]
Yess, merci ! Et ça résout les deux problèmes en même temps :-)
