### ISSUE TITLE
Installation de Geotrek-rando sur une nouvelle VM 

### ISSUE THREAD

**Issue by Max-le64** [GeotrekCE/Geotrek-rando#774]
Bonjour, nous rencontrons

 un soucis lorsque nous installons le geotrek rando sur une nouvelle vm, nous rencontrons une erreur après le «  sudo apt-get install npm » au lancement de la commande «  npm run dist » 

![image001](https://user-images.githubusercontent.com/61188011/92384571-99c7cb80-f110-11ea-9257-a00029af1dea.png)

Qu'est-ce qui pourrait provoquer cette erreur selon vous ?
 
Merci d’avance pour votre réponse.

Cordialement

**Comment by gutard** [comment]
Ça vient probablement de la version de node. Il faudrait essayer avec node v6 comme l'indique le fichier .nvmrc dans les sources. Attention à bien supprimer le répertoire node_modules pour réinitialiser l'installation. Nous avons l'habitude d'utiliser https://github.com/nvm-sh/nvm pour gérer l'installation d'une version précise de node.
