### ISSUE TITLE
problème affichage logo d'un label

### ISSUE THREAD

**Issue by pnrm** [GeotrekCE/Geotrek-rando#781]
Bonjour,
Dans la version Geotrek-rando 2.27.0 je n'arrive pas a afficher le logo du label valeurs parc dans la liste et la fiche de chaque hébergement pour ceux qui sont labellisés. J'ai une image par défaut 'http://192.168.10.14/images/approved-small.png' qui s'affiche voir ci-dessous
![image](https://user-images.githubusercontent.com/18323883/94545147-747c3800-024c-11eb-8b87-cbca33e95a1d.png)
Sous la photo de la fiche descriptive il ne trouve pas l'image http://192.168.10.14/contenu-touristique/la-montaux/images/approved-big.png
![image](https://user-images.githubusercontent.com/18323883/94545845-5f53d900-024d-11eb-8e97-3ab3b66b1c95.png)

J'ai donc ajouté les paramètres suivant dans mon fichier de configuration  'settings.custom.json'
 
```
  "APPROVED_BIG":"/custom/images/Valeurs_Parc.png",
  "APPROVED_SMALL":"/custom/images/Valeurs_Parc.png",
```
Le résultat est le même j'ai toujours l'image par défaut et pas d'image dans la fiche descriptive.
Est ce qu'il y a un autre paramètre à ajouter ou modifier ?
Merci

**Comment by camillemonchicourt** [comment]
Sur GTE, les images customisées du label sont bien visibles : http://www.grand-tour-ecrins.fr/contenu-touristique/curieux-de-nature-a-la-rencontre-des-marmottes/
Elles sont stockées dans ``/home/geotrek/Geotrek-rando/custom/public/images/epn-small.png``. Dans le fichier ``settings.custom.json`` on a renseigné ``"APPROVED_BIG": "/custom/images/epn.png",``

La documentation indique en effet que les fichiers de customisation qui doivent être accessibles en HTTP doivent être dans le dossier ``custom/public/`` : https://github.com/GeotrekCE/Geotrek-rando/blob/master/docs/settings.md#images-fonts-and-others-things

Rappel : Après chaque modification du fichier ``settings.custom.jso,``, il faut bien relancer la commande ``npm run dist`` pour appliquer les modifications.

**Comment by pnrm** [comment]
Merci Camille 
Le problème venait de mon fichier settings.custom.json ou j'avais la ligne de code APPROVED_BIG en double.
