### ISSUE TITLE
Utilisation de accessSpecificCategory dans home

### ISSUE THREAD

**Issue by MelanieMichel** [GeotrekCE/Geotrek-rando#786]
Bonjour,
J'ai créé une homepage dans GeotrekRando en suivant les modèles partagés par le PNE (merci!) .
Je rencontre une difficulté pour filtrer des catégories d'itinéraires.
Le lien suivant ne fonctionne pas : 
`<a href="#" class="cat-link" id="cat-1" ng-click="accessSpecificCategories(['T2','T4']);">Côte</a>`

Ai-je raté une astuce dans la syntaxe ?
page concernée : [http://rando.portcros-parcnational.fr](http://rando.portcros-parcnational.fr)
Merci pour les conseils

...

**Comment by camillemonchicourt** [comment]
A priori tu as nommé la fonction au pluriel ``accessSpecificCategories`` alors que son nom correct est au singulier ``accessSpecificCategory``, même si tu passes plusieurs catégories en paramètres, la fonction a toujours le même et unique nom au singulier.

La fonction est définie ici : https://github.com/GeotrekCE/Geotrek-rando/blob/master/src/app/layout/controllers.js#L58

Exemple dans notre HOME : 

```
<div>
     <a href="#" ng-click="accessSpecificCategory(['T2'])">
         <img src="/custom/images/home/grand-tour-VTT.png" alt="Grand tour en VTT">
         <h3>Un grand tour à VTT</h3>
     </a>
</div>
```

**Comment by MelanieMichel** [comment]
Merci de la réponse ! accessSpecificCategory au singulier fonctionne parfaitement.
