### ISSUE TITLE
practices order

### ISSUE THREAD

**Issue by pierreloicq** [GeotrekCE/Geotrek-rando#800]
Hi,

I did not find the way to configure the display order of the practices in geotrek rando.
I does not seem to be related to the practice ID.
Any hint ?

Thank you

**Comment by camillemonchicourt** [comment]
It is managed in Geotrek-admin database with ``order`` field in practice table : https://github.com/GeotrekCE/Geotrek-admin/commit/a9ec965d051f396a8dd4d2c733416f9e0db77def

**Comment by pierreloicq** [comment]
Great ! Thank you
