### ISSUE TITLE
Problème affichage recherche google

### ISSUE THREAD

**Issue by MNourrisson** [GeotrekCE/Geotrek-rando#806]
Bonjour,
lors de deux recherches (qui amènent aux mêmes résultats) sur google, l'affichage de la DEFAULT_META_TITLE n'est pas la même.

La DEFAULT_META_DESCRIPTION n'est elle pas prise en compte, bien qu'elle soit paramétrée.

### Actual behavior
![image](https://user-images.githubusercontent.com/34370970/100728421-d3cf0380-33c7-11eb-8e1f-8e5923c71b08.png)

![image](https://user-images.githubusercontent.com/34370970/100728493-e77a6a00-33c7-11eb-84d3-4b2967ab7a95.png)

### Steps to reproduce the behavior

[Randonnée en Livradois-Forez](https://www.google.com/search?q=randonn%C3%A9e+en+livradois+forez&rlz=1C1GCEU_frFR820FR821&oq=randonn%C3%A9e+en+li&aqs=chrome.0.0i20i263j0j69i57j0l2j69i61l3.3583j1j7&sourceid=chrome&ie=UTF-8)

[Randonnée en lf](https://www.google.com/search?rlz=1C1GCEU_frFR820FR821&ei=NBzGX4hlx6Rp7ZixsAE&q=randonn%C3%A9e+en+lf&oq=randonn%C3%A9e+en+lf&gs_lcp=CgZwc3ktYWIQAzIECAAQQzICCAAyAggAMgIIADICCAAyAggAMgIIADICCAAyAggAMgIIADoECAAQR1CljwRY-pIEYOOTBGgAcAJ4AIABe4gBzwGSAQMxLjGYAQCgAQGqAQdnd3Mtd2l6yAEIwAEB&sclient=psy-ab&ved=0ahUKEwiIz-LeyqztAhVHUhoKHW1MDBYQ4dUDCAw&uact=5)

### Specifications
* Version: 2.27.0

Si quelqu'un a une explication, je suis preneuse.
Merci,
Mélanie

**Comment by camillemonchicourt** [comment]
Le sujet est un peu différent, mais tu trouveras une partie des réponses dans ce ticket : https://github.com/GeotrekCE/Geotrek-admin/issues/2003
En effet les métadonnées sont en partie définies au niveau de Geotrek-admin, qui génèrent des fichiers HTML à plat de chaque page lors de la synchronisation.

Et c'est répercuté dans la conf NGINX de Geotrek-rando (https://github.com/GeotrekCE/Geotrek-rando/blob/master/docs/http-server.md) qui indique de prendre les pages HTML du dossier /meta/ : 
```
[...]
location @angular {
        if ($http_user_agent ~* "googlebot|yahoo|bingbot|baiduspider|yandex|yeti|yodaobot|gigabot|ia_archiver|facebookexternalhit|twitterbot|developers\.google\.com") {
            rewrite .* /meta/fr$uri/index.html last;
        }
        try_files /index.html =404;
[...]
```

**Comment by MNourrisson** [comment]
Super, merci Camille, je vais essayer.
